// ── Documents & publications ─────────────────────────────────────────────────
// One source for the /documents page and the explorer's /flattening/about.
// `kind` groups the grid; `flattening: true` marks what belongs to the
// explorer's own document list. Files live in public/docs/.

export const LINKS = {
  github:     'https://github.com/bilel-hatmi/flattening-explorer',
  pciRepo:    'https://github.com/bilel-hatmi/proximal-causal-inference',
  hawkesRepo: 'https://github.com/bilel-hatmi/hawkes-processes',
  ratesRepo:  'https://github.com/bilel-hatmi/interest-rates-project',
  cv:         '/docs/cv.pdf',
  cartesia:   '/docs/cartesia.pdf',
  essayShort: '/docs/essay_prize.pdf',
  essayFull:  '/docs/essay_full.pdf',
  poster:     '/docs/poster.pdf',
  hawkesReport: '/docs/hawkes_binned_processes.pdf',
  bloodReport:  '/docs/blood_cancers_modelling.pdf',
};

export const DOCUMENTS = [
  {
    id: 'essay-prize',
    kind: 'essay',
    flattening: true,
    href: LINKS.essayShort,
    icon: '📝',
    title: 'Prize essay',
    desc: 'The Flattening: Invisible Tail Risk in AI-Adopting Organisations. Finalist submission, Cambridge–McKinsey Risk Prize 2026.',
    badge: 'PDF',
  },
  {
    id: 'poster',
    kind: 'essay',
    flattening: true,
    href: LINKS.poster,
    icon: '🖼️',
    title: 'Poster',
    desc: 'The Flattening on a single A0 board: the bimodal loss, the correlation cascade, and the governance results at a glance.',
    badge: 'PDF',
  },
  {
    id: 'essay-full',
    kind: 'essay',
    flattening: true,
    icon: '📖',
    title: 'Full essay',
    desc: 'Extended version with complete derivations, all validation results, and the systemic policy argument. Currently being written.',
    badge: 'In progress',
    comingSoon: true,
  },
  {
    id: 'dissertation',
    kind: 'academic',
    icon: '📚',
    title: 'Part III essay',
    desc: 'Proximal Causal Inference: Theory, Methods, and Applications under Unmeasured Confounding. University of Cambridge, DPMMS, May 2026. Released once the examination process and the supervisors’ authorisation allow.',
    badge: 'Pending authorisation',
    comingSoon: true,
  },
  {
    id: 'pci-code',
    kind: 'academic',
    href: LINKS.pciRepo,
    icon: '💻',
    title: 'Proximal causal inference, code',
    desc: 'The Python library behind the essay: four estimators, six Monte Carlo diagnostics, and the blind tuning protocol that calibrates them without an oracle.',
    badge: 'GitHub',
  },
  {
    id: 'cv',
    kind: 'about',
    flattening: true,
    href: LINKS.cv,
    icon: '💼',
    title: 'Curriculum Vitae',
    desc: 'Research, education and professional experience on two pages. September 2026.',
    badge: 'PDF',
  },
  {
    id: 'source',
    kind: 'code',
    flattening: true,
    href: LINKS.github,
    icon: '💻',
    title: 'The Flattening, source code',
    desc: 'Simulation engine (Python), interactive explorer (React), all pre-computed datasets, and this site.',
    badge: 'GitHub',
  },
  {
    id: 'hawkes-report',
    kind: 'reports',
    href: LINKS.hawkesReport,
    icon: '📄',
    title: 'Parameter Estimation of Binned Hawkes Processes',
    desc: 'Group report, CentraleSupélec, supervised by Ioane Muni Toke. Maximum likelihood, Whittle and neural estimators for self-exciting point processes observed on a grid. 49 pages, English.',
    badge: 'PDF',
  },
  {
    id: 'blood-report',
    kind: 'reports',
    href: LINKS.bloodReport,
    icon: '📄',
    title: 'Modélisation de l’apparition et du développement de cancers du sang',
    desc: 'Group report, CentraleSupélec with the Gustave Roussy Institute, January 2023. Stochastic model of myeloproliferative syndromes extended to homozygous clones. 24 pages, French.',
    badge: 'PDF',
  },
  {
    id: 'hawkes-code',
    kind: 'code',
    href: LINKS.hawkesRepo,
    icon: '💻',
    title: 'Binned Hawkes processes',
    desc: 'Maximum likelihood, Whittle and neural estimators for self-exciting point processes observed on a grid. CentraleSupélec, 2023.',
    badge: 'GitHub',
  },
  {
    id: 'rates-code',
    kind: 'code',
    href: LINKS.ratesRepo,
    icon: '💻',
    title: 'Interest rate models',
    desc: 'Ho-Lee and HJM in discrete time, with a small app that prices caplets from the parameters you enter. CentraleSupélec, 2023.',
    badge: 'GitHub',
  },
  {
    id: 'cartesia',
    kind: 'venture',
    flattening: true,
    href: LINKS.cartesia,
    icon: '⬡',
    title: 'CartesIA',
    desc: 'AI-assisted introspection: what has been built, what remains unknown, and what a partnership would look like. Working document for academic and organisational partners, March 2026.',
    badge: 'PDF',
    full: true,
  },
];

export const DOCUMENT_KINDS = [
  { id: 'essay',    label: 'The Flattening' },
  { id: 'academic', label: 'Causal inference' },
  { id: 'venture',  label: 'CartesIA' },
  { id: 'reports',  label: 'Reports' },
  { id: 'code',     label: 'Code' },
  { id: 'about',    label: 'About me' },
];

export const FLATTENING_DOCUMENTS = DOCUMENTS.filter(d => d.flattening);
