// ── Documents & publications ─────────────────────────────────────────────────
// One source for the /documents page and the explorer's /flattening/about.
// `kind` groups the grid; `flattening: true` marks what belongs to the
// explorer's own document list; `type` picks the badge icon (essay, poster,
// deck, report, code, cv); `action` is the link text on the card, `secondary`
// an optional second link. Files live in public/docs/.

export const LINKS = {
  github:     'https://github.com/bilel-hatmi/flattening-explorer',
  pciRepo:    'https://github.com/bilel-hatmi/proximal-causal-inference',
  hawkesRepo: 'https://github.com/bilel-hatmi/hawkes-processes',
  ratesRepo:  'https://github.com/bilel-hatmi/interest-rates-project',
  eiRepo:     'https://github.com/bilel-hatmi/Ei_impact',
  cv:         '/docs/cv.pdf',
  cartesia:   '/docs/cartesia.pdf',
  essayShort: '/docs/essay_prize.pdf',
  essayFull:  '/docs/essay_full.pdf',
  poster:     '/docs/poster.pdf',
  essayPCI:   '/docs/part_iii_essay_pci.pdf',
  hawkesReport: '/docs/hawkes_binned_processes.pdf',
  bloodReport:  '/docs/blood_cancers_modelling.pdf',
  ratesReport:  '/docs/interest_rates_ho_lee_hjm.pdf',
  deckSycophancy: '/docs/srie/srie_sycophancy.pdf',
  deckMediation:  '/docs/srie/srie_mediation.pdf',
  deckTutor:      '/docs/srie/srie_tutor.pdf',
};

export const DOCUMENTS = [
  {
    id: 'essay-prize',
    kind: 'essay',
    flattening: true,
    href: LINKS.essayShort,
    type: 'essay',
    title: 'Prize essay',
    desc: 'The Flattening: Invisible Tail Risk in AI-Adopting Organisations. Finalist submission, Cambridge–McKinsey Risk Prize 2026.',
    badge: 'PDF',
    action: 'Read the essay',
  },
  {
    id: 'poster',
    kind: 'essay',
    flattening: true,
    href: LINKS.poster,
    type: 'poster',
    title: 'Poster',
    desc: 'The Flattening on a single A0 board: the mechanism, the bimodal loss, the correlation cascade, and the governance results at a glance.',
    badge: 'PDF',
    action: 'Open the poster',
  },
  {
    id: 'essay-full',
    kind: 'essay',
    flattening: true,
    type: 'essay',
    title: 'Full essay',
    desc: 'Extended version with complete derivations, all validation results, and the systemic policy argument. Currently being written.',
    badge: 'In progress',
    comingSoon: true,
  },
  {
    id: 'dissertation',
    kind: 'academic',
    href: LINKS.essayPCI,
    type: 'essay',
    title: 'Proximal Causal Inference: Theory, Methods, and Applications under Unmeasured Confounding',
    desc: 'Part III essay in Mathematical Statistics, University of Cambridge, DPMMS, May 2026. Supervised by Dr P. Zhao and Prof. Q. Zhao. 36 pages.',
    badge: 'PDF',
    action: 'Read the essay',
    secondary: { label: 'Project page', href: '/projects/part-iii-dissertation' },
    full: true,
  },
  {
    id: 'pci-code',
    kind: 'academic',
    href: LINKS.pciRepo,
    type: 'code',
    title: 'Proximal causal inference, code',
    desc: 'The Python library behind the essay: four estimators, six Monte Carlo diagnostics, and the blind tuning protocol that calibrates them without an oracle.',
    badge: 'GitHub',
    action: 'Browse the code',
  },
  {
    id: 'deck-sycophancy',
    kind: 'srie',
    href: LINKS.deckSycophancy,
    type: 'deck',
    title: 'Project 1 · Sycophancy as a set of constructs',
    desc: 'The project deck: diagnosis, the four quantities, two instruments across five conditions, open questions, roadmap and bibliography. 12 slides, August 2026.',
    badge: 'PDF',
    action: 'Open the deck',
  },
  {
    id: 'deck-mediation',
    kind: 'srie',
    href: LINKS.deckMediation,
    type: 'deck',
    title: 'Project 2 · Mediation under confidentiality constraints',
    desc: 'The project deck: the Anna and Ben illustration, why a model rather than a person, the optimisation problem, scope, roadmap and bibliography. 11 slides, August 2026.',
    badge: 'PDF',
    action: 'Open the deck',
  },
  {
    id: 'deck-tutor',
    kind: 'srie',
    href: LINKS.deckTutor,
    type: 'deck',
    title: 'Project 3 · An AI tutor against cognitive surrender',
    desc: 'The project deck: the deskilling evidence, knowledge spaces as the remedy, the four open questions, scope, roadmap and bibliography. 12 slides, August 2026.',
    badge: 'PDF',
    action: 'Open the deck',
  },
  {
    id: 'cv',
    kind: 'about',
    flattening: true,
    href: LINKS.cv,
    type: 'cv',
    title: 'Curriculum Vitae',
    desc: 'Research, education and professional experience on two pages. September 2026.',
    badge: 'PDF',
    action: 'Download the CV',
  },
  {
    id: 'source',
    kind: 'code',
    flattening: true,
    href: LINKS.github,
    type: 'code',
    title: 'The Flattening, source code',
    desc: 'Simulation engine (Python), interactive explorer (React), all pre-computed datasets, and this site.',
    badge: 'GitHub',
    action: 'Browse the code',
  },
  {
    id: 'hawkes-report',
    kind: 'reports',
    href: LINKS.hawkesReport,
    type: 'report',
    title: 'Parameter Estimation of Binned Hawkes Processes',
    desc: 'Group report, CentraleSupélec, February–June 2023, supervised by Ioane Muni Toke. Maximum likelihood, Whittle and neural estimators for self-exciting point processes observed on a grid. 49 pages, English.',
    badge: 'PDF',
    action: 'Read the report',
  },
  {
    id: 'blood-report',
    kind: 'reports',
    href: LINKS.bloodReport,
    type: 'report',
    title: 'Modélisation de l’apparition et du développement de cancers du sang',
    desc: 'Group report, CentraleSupélec with the Gustave Roussy Institute, September 2022–January 2023. Stochastic model of myeloproliferative syndromes extended to homozygous clones. 24 pages, French.',
    badge: 'PDF',
    action: 'Read the report',
  },
  {
    id: 'rates-report',
    kind: 'reports',
    href: LINKS.ratesReport,
    type: 'report',
    title: 'Modélisation stochastique de taux d’intérêts en temps discret',
    desc: 'Group report, CentraleSupélec, February–June 2023. Ho-Lee and HJM in discrete time: zero-coupon and caplet pricing, calibration to the Black model, asymptotic equivalence of the two models. 14 pages, French.',
    badge: 'PDF',
    action: 'Read the report',
  },
  {
    id: 'hawkes-code',
    kind: 'code',
    href: LINKS.hawkesRepo,
    type: 'code',
    title: 'Binned Hawkes processes',
    desc: 'Maximum likelihood, Whittle and neural estimators for self-exciting point processes observed on a grid. CentraleSupélec, 2023.',
    badge: 'GitHub',
    action: 'Browse the code',
  },
  {
    id: 'rates-code',
    kind: 'code',
    href: LINKS.ratesRepo,
    type: 'code',
    title: 'Interest rate models',
    desc: 'Ho-Lee and HJM in discrete time, with a small app that prices caplets from the parameters you enter. CentraleSupélec, 2023.',
    badge: 'GitHub',
    action: 'Browse the code',
  },
  {
    id: 'ei-code',
    kind: 'code',
    href: LINKS.eiRepo,
    type: 'code',
    title: 'Well-being impact model',
    desc: 'The code that followed the Elements Impact internship: a Streamlit application with the predictive model and its parametrisation. 2023.',
    badge: 'GitHub',
    action: 'Browse the code',
  },
  {
    id: 'cartesia',
    kind: 'venture',
    flattening: true,
    href: LINKS.cartesia,
    type: 'pdf',
    logo: '/img/cartesia_mark.png',
    title: 'CartesIA',
    desc: 'AI-assisted introspection: what was built, what remains unknown, and what a partnership would look like. Working document for academic and organisational partners, March 2026. The project is paused.',
    badge: 'PDF',
    action: 'Read the presentation',
    secondary: { label: 'Project page', href: '/projects/cartesia' },
    full: true,
  },
];

export const DOCUMENT_KINDS = [
  { id: 'essay',    label: 'The Flattening' },
  { id: 'academic', label: 'Causal inference' },
  { id: 'srie',     label: 'SRIE, the three project decks' },
  { id: 'reports',  label: 'Reports' },
  { id: 'code',     label: 'Code' },
  { id: 'venture',  label: 'CartesIA' },
  { id: 'about',    label: 'About me' },
];

export const FLATTENING_DOCUMENTS = DOCUMENTS.filter(d => d.flattening);
